INSERT INTO GM_CATEGORIE ( CAT_CODE#, CAT_LIBELLE, CAT_MONTANT ) VALUES ( 
'10', 'CADRE', 6000); 
INSERT INTO GM_CATEGORIE ( CAT_CODE#, CAT_LIBELLE, CAT_MONTANT ) VALUES ( 
'20', 'MAITRISE', 4000); 
INSERT INTO GM_CATEGORIE ( CAT_CODE#, CAT_LIBELLE, CAT_MONTANT ) VALUES ( 
'30', 'EMPLOYE', 4000); 
INSERT INTO GM_CATEGORIE ( CAT_CODE#, CAT_LIBELLE, CAT_MONTANT ) VALUES ( 
'40', 'OUVRIER', 4000); 
INSERT INTO GM_CATEGORIE ( CAT_CODE#, CAT_LIBELLE, CAT_MONTANT ) VALUES ( 
'50', 'MANOEUVRE', 4000); 
commit;
 
