INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
638500, 'FRAIS DE MISSION'); 
INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
614000, 'FRAIS DE TRANSPORT PERSONNEL'); 
INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
614100, 'TRANSPORT BAGAGE ET ENGIN'); 
INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
645800, 'TAXES ROUTIERES'); 
INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
624300, 'FRAIS DE COLLAGE'); 
INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
638400, 'FRAIS DE CASSE-CROÛTE'); 
INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
50110, 'DMCCS'); 
INSERT INTO GM_COMPTE ( COMPTE_CODE#, COMPTE_INTITULE ) VALUES ( 
999999, 'FRAIS DE COLIS'); 
commit;
 
