INSERT INTO GM_DIRECTEUR_GENERAL ( DG_CODE#, DG_LIBELLE, DG_TITRE1, DG_TITRE2, DG_NOM,
DG_PRENOM ) VALUES ( 
'DG', 'DIRECTEUR GENERAL', 'LE DIRECTEUR GENERAL', 'CHEVALIER DE L''ORDRE NATIONAL'
, 'KABORE', 'SALIF L.'); 
commit;
 
