INSERT INTO GM_EDITION ( ETAT_NOM, ETAT_LIBELLE ) VALUES ( 
'ETAT_MISSION_ANNULEES', 'ETAT DES MISSIONS ANNULEES'); 
INSERT INTO GM_EDITION ( ETAT_NOM, ETAT_LIBELLE ) VALUES ( 
'ETAT_MISSION_A_CLOTURER', 'ETAT DES MISSIONS A CLÔTURER'); 
INSERT INTO GM_EDITION ( ETAT_NOM, ETAT_LIBELLE ) VALUES ( 
'ETAT_MISSION_A_VALIDER', 'ETAT DES MISSIONS A VALIDER'); 
commit;
 
