INSERT INTO GM_ETAT ( ETAT_CODE#, ETAT_LIBELLE ) VALUES ( 
'N', 'NOUVEAU'); 
INSERT INTO GM_ETAT ( ETAT_CODE#, ETAT_LIBELLE ) VALUES ( 
'A', 'ANNULE'); 
INSERT INTO GM_ETAT ( ETAT_CODE#, ETAT_LIBELLE ) VALUES ( 
'E', 'EXECUTE'); 
INSERT INTO GM_ETAT ( ETAT_CODE#, ETAT_LIBELLE ) VALUES ( 
'V', 'VALIDE'); 
INSERT INTO GM_ETAT ( ETAT_CODE#, ETAT_LIBELLE ) VALUES ( 
'G', 'PIECE GENEREE'); 
INSERT INTO GM_ETAT ( ETAT_CODE#, ETAT_LIBELLE ) VALUES ( 
'C', 'CLOTURE'); 
commit;
 
