INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
1, 'Un'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
2, 'Deux'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
3, 'Trois'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
4, 'Quatre'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
5, 'Cinq'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
6, 'Six'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
7, 'Sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
8, 'Huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
9, 'Neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
10, 'Dix'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
11, 'Onze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
12, 'Douze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
13, 'Treize'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
14, 'Quatorze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
15, 'Quinze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
16, 'Seize'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
17, 'Dix-sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
18, 'Dix-huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
19, 'Dix-neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
20, 'Vingt'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
21, 'Vingt-et-un'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
22, 'Vingt deux'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
23, 'Vingt trois'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
24, 'Vingt quatre'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
25, 'Vingt cinq'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
26, 'Vingt six'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
27, 'Vingt sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
28, 'Vingt huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
29, 'Vingt neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
30, 'Trente'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
31, 'Trente-et-un'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
32, 'Trente deux'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
33, 'Trente trois'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
34, 'Trente quatre'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
35, 'Trente cinq'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
36, 'Trente six'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
37, 'Trente sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
38, 'Trente huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
39, 'Trente neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
40, 'Quarente'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
41, 'Quarante-et-un'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
42, 'Quarante deux'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
43, 'Quarante trois'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
44, 'Quarante quatre'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
45, 'Quarante cinq'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
46, 'Quarante six'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
47, 'Quarante sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
48, 'Quarante huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
49, 'Quarante neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
50, 'Cinquante'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
51, 'Cinquante-et-un'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
52, 'Cinquante deux'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
53, 'Cinquante trois'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
54, 'Cinquante quatre'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
55, 'Cinquante cinq'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
56, 'Cinquante six'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
57, 'Cinquante sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
58, 'Cinquante huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
59, 'Cinquante neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
60, 'Soixante'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
61, 'Soixante-et-un'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
62, 'Soixante deux'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
63, 'Soixante trois'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
64, 'Soixante quatre'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
65, 'Soixante cinq'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
66, 'Soixante six'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
67, 'Soixante sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
68, 'Soixante huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
69, 'Soixante neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
70, 'Soixante-et-dix'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
71, 'Soixante onze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
72, 'Soixante douze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
73, 'Soixante treize'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
74, 'Soixante quatorze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
75, 'Soixante quinze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
76, 'Soixante seize'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
77, 'Soixante dix-sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
78, 'Soixante dix-huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
79, 'Soixante dix-neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
80, 'Quatre-vinqt'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
81, 'Quatre-vinqt-et-un'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
82, 'Quatre-vinqt deux'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
83, 'Quatre-vinqt trois'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
84, 'Quatre-vinqt quatre'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
85, 'Quatre-vinqt cinq'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
86, 'Quatre-vinqt six'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
87, 'Quatre-vinqt sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
88, 'Quatre-vinqt huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
89, 'Quatre-vinqt neuf'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
90, 'Quatre-vinqt-dix'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
91, 'Quatre-vingt-onze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
92, 'Quatre-vinqt-douze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
93, 'Quatre-vinqt-treize'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
94, 'Quatre-vinqt-quatorze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
95, 'Quatre-vinqt-quinze'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
96, 'Quatre-vinqt-seize'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
97, 'Quatre-vinqt-dix-sept'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
98, 'Quatre-vinqtdix-huit'); 
INSERT INTO GM_NOMBRE ( NOMBRE, LETTRE ) VALUES ( 
99, 'Quatre-vinqt-dix-neuf'); 
commit;
 
