INSERT INTO GM_SIGNATAIRE ( SIGNATAIRE_CODE#, SIGNATAIRE_NOM, SIGNATAIRE_PRENOM, SIGNATAIRE_TITRE1,
SIGNATAIRE_TITRE2 ) VALUES ( 
'DFC', 'KABORE', 'JEAN BAPTISTE', 'LE DIRECTEUR FINANCIER ET COMPTABLE', 'CHEVALIER DE L''ORDRE NATIONAL'); 
INSERT INTO GM_SIGNATAIRE ( SIGNATAIRE_CODE#, SIGNATAIRE_NOM, SIGNATAIRE_PRENOM, SIGNATAIRE_TITRE1,
SIGNATAIRE_TITRE2 ) VALUES ( 
'DEPE', 'SAWADOGO', 'R. NARCISSE', 'LE DIRECTEUR DES ETUDES DE LA PLANIFICATION ET DE L''EQUIPEMENT'
, 'CHEVALIER DE L''ORDRE NATIONAL'); 
INSERT INTO GM_SIGNATAIRE ( SIGNATAIRE_CODE#, SIGNATAIRE_NOM, SIGNATAIRE_PRENOM, SIGNATAIRE_TITRE1,
SIGNATAIRE_TITRE2 ) VALUES ( 
'DCE', 'COMPAORE', 'SENI', 'LE DIRECTEUR DES CENTRES EXTERIEURS', 'CHEVALIER DE L''ORDRE NATIONAL'); 
INSERT INTO GM_SIGNATAIRE ( SIGNATAIRE_CODE#, SIGNATAIRE_NOM, SIGNATAIRE_PRENOM, SIGNATAIRE_TITRE1,
SIGNATAIRE_TITRE2 ) VALUES ( 
'DRH', 'OUATTARA', 'HEMA MOUSSA', 'LE DIRECTEUR RESSOURCES HUMAINES', 'CHEVALIER DE L''ORDRE NATIONAL'); 
INSERT INTO GM_SIGNATAIRE ( SIGNATAIRE_CODE#, SIGNATAIRE_NOM, SIGNATAIRE_PRENOM, SIGNATAIRE_TITRE1,
SIGNATAIRE_TITRE2 ) VALUES ( 
'DD', 'OUEDRAOGO', 'FRANCOIS DE SALLE', 'LE DIRECETUR DE LA DISTRIBUTION', 'CHEVALIER DE L''ORDRE NATIONAL'); 
commit;
 
