INSERT INTO GM_VEHICULE ( IMMATRICULATION# ) VALUES ( 
'11 TT 0118'); 
INSERT INTO GM_VEHICULE ( IMMATRICULATION# ) VALUES ( 
'TRANSPORTEUR'); 
INSERT INTO GM_VEHICULE ( IMMATRICULATION# ) VALUES ( 
'11 E 1510 BF'); 
commit;
 
