CREATE TABLE GM_ACCOMPAGNANT ( 
  CHEF_MATRICULE#  VARCHAR2 (8)  NOT NULL, 
  ACC_MATRICULE#   VARCHAR2 (8)  NOT NULL, 
  MISSION_NUMERO#  VARCHAR2 (10)  NOT NULL, 
  ACC_NOM          VARCHAR2 (25)  NOT NULL, 
  ACC_PRENOM       VARCHAR2 (25)  NOT NULL, 
  ACC_FONCTION     VARCHAR2 (100)  NOT NULL, 
  ACC_ADRESSE      VARCHAR2 (50), 
  ACC_TELEPHONE    VARCHAR2 (20), 
  CAT_CODE#        VARCHAR2 (2)  NOT NULL, 
  CHAUFFEUR        VARCHAR2 (1)  NOT NULL, 
  ACC_DATE_RETOUR  DATE ) ;

CREATE TABLE GM_CATEGORIE ( 
  CAT_CODE#    VARCHAR2 (2)  NOT NULL, 
  CAT_LIBELLE  VARCHAR2 (60)  NOT NULL, 
  CAT_MONTANT  NUMBER (12)   NOT NULL, 
  CONSTRAINT PK_GM_CATEGORIE
  PRIMARY KEY ( CAT_CODE# ) ) ;

CREATE TABLE GM_COMPTE ( 
  COMPTE_CODE#     NUMBER        NOT NULL, 
  COMPTE_INTITULE  VARCHAR2 (100)  NOT NULL, 
  CONSTRAINT PK_GM_COMPTE
  PRIMARY KEY ( COMPTE_CODE# ) ) ;

CREATE TABLE GM_DESTINATION ( 
  MISSION_NUMERO#           VARCHAR2 (10)  NOT NULL, 
  DESTINATION_LIBELLE       VARCHAR2 (200)  NOT NULL, 
  DESTINATION_DATE_ARRIVEE  DATE          NOT NULL ) ; 

CREATE TABLE GM_DIRECTEUR_GENERAL ( 
  DG_CODE#    VARCHAR2 (20)  NOT NULL, 
  DG_LIBELLE  VARCHAR2 (60)  NOT NULL, 
  DG_TITRE1   VARCHAR2 (100), 
  DG_TITRE2   VARCHAR2 (100), 
  DG_NOM      VARCHAR2 (20), 
  DG_PRENOM   VARCHAR2 (30), 
  CONSTRAINT PK_GM_DIRECTEUR_GENERAL
  PRIMARY KEY ( DG_CODE# ) ) ; 

CREATE TABLE GM_EDITION ( 
  ETAT_NOM      VARCHAR2 (100)  NOT NULL, 
  ETAT_LIBELLE  VARCHAR2 (100)  NOT NULL, 
  CONSTRAINT PK_GM_EDITION
  PRIMARY KEY ( ETAT_NOM ) ) ; 

CREATE TABLE GM_ETAT ( 
  ETAT_CODE#    VARCHAR2 (1)  NOT NULL, 
  ETAT_LIBELLE  VARCHAR2 (60)  NOT NULL, 
  CONSTRAINT PK_GM_ETAT
  PRIMARY KEY ( ETAT_CODE# ) ) ; 

CREATE TABLE GM_FONCTION ( 
  AGENT_MATRICULE#  VARCHAR2 (8)  NOT NULL, 
  MISSION_NUMERO#   VARCHAR2 (10)  NOT NULL, 
  FONCTION_LIBELLE  VARCHAR2 (100)  NOT NULL ) ; 

CREATE TABLE GM_LIEU_AFFECTATION ( 
  AGENT_MATRICULE#  VARCHAR2 (8)  NOT NULL, 
  MISSION_NUMERO#   VARCHAR2 (10)  NOT NULL, 
  LIEU_AFFECTATION  VARCHAR2 (60)  NOT NULL ) ; 

CREATE TABLE GM_MISSION ( 
  MISSION_NUMERO#         VARCHAR2 (10)  NOT NULL, 
  MISSION_OBJET           VARCHAR2 (200)  NOT NULL, 
  MISSION_DATE_DEPART     DATE          NOT NULL, 
  MISSION_DATE_RETOUR     DATE          NOT NULL, 
  MISSION_OBS_HIERARCHIE  VARCHAR2 (100)  NOT NULL, 
  MISSION_USER_CREATE     VARCHAR2 (30)  NOT NULL, 
  MISSION_DATE_CREATE     DATE          NOT NULL, 
  MISSION_MACHINE_CREATE  VARCHAR2 (30)  NOT NULL, 
  MISSION_USER_UPDATE     VARCHAR2 (30)  NOT NULL, 
  MISSION_DATE_UPDATE     DATE          NOT NULL, 
  MISSION_MACHINE_UPDATE  VARCHAR2 (30)  NOT NULL, 
  AG_MATRICULE#           VARCHAR2 (8)  NOT NULL, 
  ETAT_CODE#              VARCHAR2 (1)  NOT NULL, 
  SIGNATAIRE_CODE#        VARCHAR2 (10)  NOT NULL, 
  CAT_CODE#               VARCHAR2 (2)  NOT NULL, 
  DG_CODE#                VARCHAR2 (20)  NOT NULL, 
  CHAUFFEUR               VARCHAR2 (1)  NOT NULL, 
  UNIQUE (MISSION_NUMERO#), 
  CONSTRAINT PK_GM_MISSION
  PRIMARY KEY ( MISSION_NUMERO# ) ) ; 

CREATE TABLE GM_NOMBRE ( 
  NOMBRE  NUMBER        NOT NULL, 
  LETTRE  VARCHAR2 (35)  NOT NULL ) ; 

CREATE TABLE GM_PIECE_DEPENSE ( 
  COMPTE_CODE#         NUMBER        NOT NULL, 
  AG_MATRICULE#        VARCHAR2 (8)  NOT NULL, 
  SERVICE_CODE#        VARCHAR2 (10)  NOT NULL, 
  PD_MONTANT           NUMBER        NOT NULL, 
  CENTRE_DE_COUT       NUMBER        NOT NULL, 
  MISSION_NUMERO#      VARCHAR2 (10)  NOT NULL, 
  USER_DATE_CREATE     DATE, 
  USER_MACHINE_CREATE  VARCHAR2 (30), 
  USER_CREATE          VARCHAR2 (30) ) ; 

CREATE TABLE GM_SIGNATAIRE ( 
  SIGNATAIRE_CODE#   VARCHAR2 (10)  NOT NULL, 
  SIGNATAIRE_NOM     VARCHAR2 (20)  NOT NULL, 
  SIGNATAIRE_PRENOM  VARCHAR2 (30)  NOT NULL, 
  SIGNATAIRE_TITRE1  VARCHAR2 (100)  NOT NULL, 
  SIGNATAIRE_TITRE2  VARCHAR2 (100)  NOT NULL, 
  CONSTRAINT PK_GM_SIGNATAIRE
  PRIMARY KEY ( SIGNATAIRE_CODE# ) ) ; 

CREATE TABLE GM_VEHICULE ( 
  IMMATRICULATION#  VARCHAR2 (50)  NOT NULL, 
  CONSTRAINT PK_GM_VEHICULE
  PRIMARY KEY ( IMMATRICULATION# ) ) ; 

CREATE TABLE GM_VEHICULE_MISSION ( 
  MISSION_NUMERO#   VARCHAR2 (10)  NOT NULL, 
  IMMATRICULATION#  VARCHAR2 (50)  NOT NULL ) ; 

CREATE TABLE GM_CHAUFFEUR ( 
  CH_MATRICULE#  VARCHAR2 (8)  NOT NULL, 
  CH_NOM         VARCHAR2 (25)  NOT NULL, 
  CH_PRENOM      VARCHAR2 (25)  NOT NULL, 
  CH_TELEPHONE   VARCHAR2 (20), 
  CONSTRAINT PK_GM_CHAUFFEUR
  PRIMARY KEY ( CH_MATRICULE# ) ) ;

CREATE TABLE GM_CHAUFFEUR_MISSION ( 
  MISSION_NUMERO#  VARCHAR2 (10)  NOT NULL, 
  CH_MATRICULE#    VARCHAR2 (8)  NOT NULL, 
  CH_DATE_DEPART   DATE          NOT NULL, 
  CH_DATE_RETOUR   DATE          NOT NULL ) ; 

CREATE TABLE GM_INCIDENCE_FINANCIERE ( 
  IF_CODE#    VARCHAR2 (2)  NOT NULL, 
  IF_LIBELLE  VARCHAR2 (100)  NOT NULL, 
  CONSTRAINT PK_GM_INCIDENCE_FINANCIERE
  PRIMARY KEY ( IF_CODE# ) ) ; 