INSERT INTO gm_nombre VALUES(1, 'Un');                                          
INSERT INTO gm_nombre VALUES(2, 'Deux');                                        
INSERT INTO gm_nombre VALUES(3, 'Trois');                                       
INSERT INTO gm_nombre VALUES(4, 'Quatre');                                      
INSERT INTO gm_nombre VALUES(5, 'Cinq');                                        
INSERT INTO gm_nombre VALUES(6, 'Six');                                         
INSERT INTO gm_nombre VALUES(7, 'Sept');                                        
INSERT INTO gm_nombre VALUES(8, 'Huit');                                        
INSERT INTO gm_nombre VALUES(9, 'Neuf');                                        
INSERT INTO gm_nombre VALUES(10, 'Dix');                                        
INSERT INTO gm_nombre VALUES(11, 'Onze');                                       
INSERT INTO gm_nombre VALUES(12, 'Douze');                                      
INSERT INTO gm_nombre VALUES(13, 'Treize');                                     
INSERT INTO gm_nombre VALUES(14, 'Quatorze');                                   
INSERT INTO gm_nombre VALUES(15, 'Quinze');                                     
INSERT INTO gm_nombre VALUES(16, 'Seize');                                      
INSERT INTO gm_nombre VALUES(17, 'Dix-sept');                                   
INSERT INTO gm_nombre VALUES(18, 'Dix-huit');                                   
INSERT INTO gm_nombre VALUES(19, 'Dix-neuf');                                   
INSERT INTO gm_nombre VALUES(20, 'Vingt');                                      
INSERT INTO gm_nombre VALUES(21, 'Vingt-et-un');                                
INSERT INTO gm_nombre VALUES(22, 'Vingt deux');                                 
INSERT INTO gm_nombre VALUES(23, 'Vingt trois');                                
INSERT INTO gm_nombre VALUES(24, 'Vingt quatre');                               
INSERT INTO gm_nombre VALUES(25, 'Vingt cinq');                                 
INSERT INTO gm_nombre VALUES(26, 'Vingt six');                                  
INSERT INTO gm_nombre VALUES(27, 'Vingt sept');                                 
INSERT INTO gm_nombre VALUES(28, 'Vingt huit');                                 
INSERT INTO gm_nombre VALUES(29, 'Vingt neuf');                                 
INSERT INTO gm_nombre VALUES(30, 'Trente');                                     
INSERT INTO gm_nombre VALUES(31, 'Trente-et-un');                               
INSERT INTO gm_nombre VALUES(32, 'Trente deux');                                
INSERT INTO gm_nombre VALUES(33, 'Trente trois');                               
INSERT INTO gm_nombre VALUES(34, 'Trente quatre');                              
INSERT INTO gm_nombre VALUES(35, 'Trente cinq');                                
INSERT INTO gm_nombre VALUES(36, 'Trente six');                                 
INSERT INTO gm_nombre VALUES(37, 'Trente sept');                                
INSERT INTO gm_nombre VALUES(38, 'Trente huit');                                
INSERT INTO gm_nombre VALUES(39, 'Trente neuf');                                
INSERT INTO gm_nombre VALUES(40, 'Quarente');                                   
INSERT INTO gm_nombre VALUES(41, 'Quarante-et-un');                             
INSERT INTO gm_nombre VALUES(42, 'Quarante deux');                              
INSERT INTO gm_nombre VALUES(43, 'Quarante trois');                             
INSERT INTO gm_nombre VALUES(44, 'Quarante quatre');                            
INSERT INTO gm_nombre VALUES(45, 'Quarante cinq');                              
INSERT INTO gm_nombre VALUES(46, 'Quarante six');                               
INSERT INTO gm_nombre VALUES(47, 'Quarante sept');                              
INSERT INTO gm_nombre VALUES(48, 'Quarante huit');                              
INSERT INTO gm_nombre VALUES(49, 'Quarante neuf');                              
INSERT INTO gm_nombre VALUES(50, 'Cinquante');                                  
INSERT INTO gm_nombre VALUES(51, 'Cinquante-et-un');                            
INSERT INTO gm_nombre VALUES(52, 'Cinquante deux');                             
INSERT INTO gm_nombre VALUES(53, 'Cinquante trois');                            
INSERT INTO gm_nombre VALUES(54, 'Cinquante quatre');                           
INSERT INTO gm_nombre VALUES(55, 'Cinquante cinq');                             
INSERT INTO gm_nombre VALUES(56, 'Cinquante six');                              
INSERT INTO gm_nombre VALUES(57, 'Cinquante sept');                             
INSERT INTO gm_nombre VALUES(58, 'Cinquante huit');                             
INSERT INTO gm_nombre VALUES(59, 'Cinquante neuf');                             
INSERT INTO gm_nombre VALUES(60, 'Soixante');                                   
INSERT INTO gm_nombre VALUES(61, 'Soixante-et-un');                             
INSERT INTO gm_nombre VALUES(62, 'Soixante deux');                              
INSERT INTO gm_nombre VALUES(63, 'Soixante trois');                             
INSERT INTO gm_nombre VALUES(64, 'Soixante quatre');                            
INSERT INTO gm_nombre VALUES(65, 'Soixante cinq');                              
INSERT INTO gm_nombre VALUES(66, 'Soixante six');                               
INSERT INTO gm_nombre VALUES(67, 'Soixante sept');                              
INSERT INTO gm_nombre VALUES(68, 'Soixante huit');                              
INSERT INTO gm_nombre VALUES(69, 'Soixante neuf');                              
INSERT INTO gm_nombre VALUES(70, 'Soixante-et-dix');                            
INSERT INTO gm_nombre VALUES(71, 'Soixante onze');                              
INSERT INTO gm_nombre VALUES(72, 'Soixante douze');                             
INSERT INTO gm_nombre VALUES(73, 'Soixante treize');                            
INSERT INTO gm_nombre VALUES(74, 'Soixante quatorze');                          
INSERT INTO gm_nombre VALUES(75, 'Soixante quinze');                            
INSERT INTO gm_nombre VALUES(76, 'Soixante seize');                             
INSERT INTO gm_nombre VALUES(77, 'Soixante dix-sept');                          
INSERT INTO gm_nombre VALUES(78, 'Soixante dix-huit');                          
INSERT INTO gm_nombre VALUES(79, 'Soixante dix-neuf');                          
INSERT INTO gm_nombre VALUES(80, 'Quatre-vinqt');                               
INSERT INTO gm_nombre VALUES(81, 'Quatre-vinqt-et-un');                         
INSERT INTO gm_nombre VALUES(82, 'Quatre-vinqt deux');                          
INSERT INTO gm_nombre VALUES(83, 'Quatre-vinqt trois');                         
INSERT INTO gm_nombre VALUES(84, 'Quatre-vinqt quatre');                        
INSERT INTO gm_nombre VALUES(85, 'Quatre-vinqt cinq');                          
INSERT INTO gm_nombre VALUES(86, 'Quatre-vinqt six');                           
INSERT INTO gm_nombre VALUES(87, 'Quatre-vinqt sept');                          
INSERT INTO gm_nombre VALUES(88, 'Quatre-vinqt huit');                          
INSERT INTO gm_nombre VALUES(89, 'Quatre-vinqt neuf');                          
INSERT INTO gm_nombre VALUES(90, 'Quatre-vinqt-dix');                           
INSERT INTO gm_nombre VALUES(91, 'Quatre-vingt-onze');                          
INSERT INTO gm_nombre VALUES(92, 'Quatre-vinqt-douze');                         
INSERT INTO gm_nombre VALUES(93, 'Quatre-vinqt-treize');                        
INSERT INTO gm_nombre VALUES(94, 'Quatre-vinqt-quatorze');                      
INSERT INTO gm_nombre VALUES(95, 'Quatre-vinqt-quinze');                        
INSERT INTO gm_nombre VALUES(96, 'Quatre-vinqt-seize');                         
INSERT INTO gm_nombre VALUES(97, 'Quatre-vinqt-dix-sept');                      
INSERT INTO gm_nombre VALUES(98, 'Quatre-vinqtdix-huit');                       
INSERT INTO gm_nombre VALUES(99, 'Quatre-vinqt-dix-neuf');
commit;                      